export const topicStarters = [
  // Cars (25 topics)
  { interest: 'Cars', topic: 'What was your first car?', used: false },
  { interest: 'Cars', topic: 'If you could own any car in the world, what would it be?', used: false },
  { interest: 'Cars', topic: 'What\'s your opinion on electric cars?', used: false },
  { interest: 'Cars', topic: 'Do you prefer manual or automatic transmission?', used: false },
  { interest: 'Cars', topic: 'What\'s the longest road trip you\'ve ever taken?', used: false },
  { interest: 'Cars', topic: 'What\'s your dream car and why?', used: false },
  { interest: 'Cars', topic: 'Do you think self-driving cars will become the norm?', used: false },
  { interest: 'Cars', topic: 'What\'s the most interesting car feature you\'ve seen?', used: false },
  { interest: 'Cars', topic: 'If you could design a car, what would be its standout feature?', used: false },
  { interest: 'Cars', topic: 'What\'s your favorite car brand and why?', used: false },
  { interest: 'Cars', topic: 'Do you enjoy working on cars yourself or prefer leaving it to professionals?', used: false },
  { interest: 'Cars', topic: 'What\'s your opinion on hybrid vehicles?', used: false },
  { interest: 'Cars', topic: 'If you could bring back any discontinued car model, which would it be?', used: false },
  { interest: 'Cars', topic: 'What\'s the most memorable car commercial you\'ve seen?', used: false },
  { interest: 'Cars', topic: 'Do you think flying cars will ever become a reality?', used: false },
  { interest: 'Cars', topic: 'What\'s your favorite car movie scene?', used: false },
  { interest: 'Cars', topic: 'If you could go on a road trip with any famous person, who would it be and where would you go?', used: false },
  { interest: 'Cars', topic: 'What\'s your opinion on car-sharing services?', used: false },
  { interest: 'Cars', topic: 'Do you have any interesting car-related stories or experiences?', used: false },
  { interest: 'Cars', topic: 'What\'s the most unusual car you\'ve ever seen or ridden in?', used: false },
  { interest: 'Cars', topic: 'If you could attend any car show or racing event, which would it be?', used: false },
  { interest: 'Cars', topic: 'What do you think cars will look like 50 years from now?', used: false },
  { interest: 'Cars', topic: 'Do you have a favorite era of car design?', used: false },
  { interest: 'Cars', topic: 'What\'s your opinion on car customization and modifications?', used: false },
  { interest: 'Cars', topic: 'If you could own a famous car from a movie or TV show, which would it be?', used: false },

  // Tech (25 topics)
  { interest: 'Tech', topic: 'What\'s the most exciting tech innovation you\'ve seen recently?', used: false },
  { interest: 'Tech', topic: 'Do you think AI will replace human jobs in the future?', used: false },
  { interest: 'Tech', topic: 'What\'s your favorite smartphone app and why?', used: false },
  { interest: 'Tech', topic: 'How do you think virtual reality will change our lives?', used: false },
  { interest: 'Tech', topic: 'What\'s your opinion on cryptocurrency?', used: false },
  { interest: 'Tech', topic: 'What tech gadget can\'t you live without?', used: false },
  { interest: 'Tech', topic: 'Do you think we\'ll ever achieve true artificial general intelligence?', used: false },
  { interest: 'Tech', topic: 'What\'s your favorite tech company and why?', used: false },
  { interest: 'Tech', topic: 'How do you think 5G will impact our daily lives?', used: false },
  { interest: 'Tech', topic: 'What\'s your opinion on social media\'s impact on society?', used: false },
  { interest: 'Tech', topic: 'Do you prefer iOS or Android? Why?', used: false },
  { interest: 'Tech', topic: 'What\'s the most useful tech skill you\'ve learned?', used: false },
  { interest: 'Tech', topic: 'How do you think quantum computing will change technology?', used: false },
  { interest: 'Tech', topic: 'What\'s your favorite tech podcast or YouTube channel?', used: false },
  { interest: 'Tech', topic: 'Do you think we\'ll ever colonize Mars?', used: false },
  { interest: 'Tech', topic: 'What\'s your opinion on the Internet of Things (IoT)?', used: false },
  { interest: 'Tech', topic: 'How do you stay up-to-date with the latest tech news?', used: false },
  { interest: 'Tech', topic: 'What\'s the most interesting tech conference or event you\'ve attended?', used: false },
  { interest: 'Tech', topic: 'Do you think technology is making us more or less connected as humans?', used: false },
  { interest: 'Tech', topic: 'What\'s your favorite tech-related movie or TV show?', used: false },
  { interest: 'Tech', topic: 'How do you think blockchain technology will impact various industries?', used: false },
  { interest: 'Tech', topic: 'What\'s your opinion on the right to repair movement?', used: false },
  { interest: 'Tech', topic: 'Do you think we\'ll ever achieve sustainable fusion energy?', used: false },
  { interest: 'Tech', topic: 'What\'s the most impressive tech demo you\'ve ever seen?', used: false },
  { interest: 'Tech', topic: 'How do you think technology will change education in the coming years?', used: false },

  // Animals (25 topics)
  { interest: 'Animals', topic: 'What\'s your favorite animal and why?', used: false },
  { interest: 'Animals', topic: 'Do you have any pets? If so, tell me about them.', used: false },
  { interest: 'Animals', topic: 'What\'s the most interesting animal fact you know?', used: false },
  { interest: 'Animals', topic: 'If you could be any animal for a day, which would you choose?', used: false },
  { interest: 'Animals', topic: 'What\'s your opinion on zoos?', used: false },
  { interest: 'Animals', topic: 'Have you ever had an unusual animal encounter?', used: false },
  { interest: 'Animals', topic: 'What\'s your favorite marine animal?', used: false },
  { interest: 'Animals', topic: 'Do you think animals have emotions like humans do?', used: false },
  { interest: 'Animals', topic: 'What\'s the most exotic animal you\'ve seen in person?', used: false },
  { interest: 'Animals', topic: 'If you could bring back an extinct animal, which would it be?', used: false },
  { interest: 'Animals', topic: 'What\'s your favorite bird species?', used: false },
  { interest: 'Animals', topic: 'Do you have a favorite animal-related movie or documentary?', used: false },
  { interest: 'Animals', topic: 'What\'s your opinion on animal testing?', used: false },
  { interest: 'Animals', topic: 'Have you ever volunteered at an animal shelter?', used: false },
  { interest: 'Animals', topic: 'What\'s the most intelligent animal in your opinion?', used: false },
  { interest: 'Animals', topic: 'Do you have a favorite animal-related book?', used: false },
  { interest: 'Animals', topic: 'What\'s your opinion on keeping exotic pets?', used: false },
  { interest: 'Animals', topic: 'Have you ever been to a wildlife sanctuary?', used: false },
  { interest: 'Animals', topic: 'What\'s your favorite insect and why?', used: false },
  { interest: 'Animals', topic: 'Do you think we should clone extinct animals if we could?', used: false },
  { interest: 'Animals', topic: 'What\'s the most unusual animal adaptation you know of?', used: false },
  { interest: 'Animals', topic: 'Have you ever seen a rare or endangered animal in the wild?', used: false },
  { interest: 'Animals', topic: 'What\'s your opinion on animal rights?', used: false },
  { interest: 'Animals', topic: 'If you could communicate with any animal, which would it be?', used: false },
  { interest: 'Animals', topic: 'What\'s the most fascinating animal behavior you\'ve observed?', used: false },

  // Cooking (25 topics)
  { interest: 'Cooking', topic: 'What\'s your favorite dish to cook?', used: false },
  { interest: 'Cooking', topic: 'Do you have a family recipe that\'s been passed down?', used: false },
  { interest: 'Cooking', topic: 'What\'s the most challenging dish you\'ve ever attempted?', used: false },
  { interest: 'Cooking', topic: 'Do you prefer cooking or baking?', used: false },
  { interest: 'Cooking', topic: 'What\'s your go-to comfort food?', used: false },
  { interest: 'Cooking', topic: 'Have you ever taken a cooking class?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite cuisine?', used: false },
  { interest: 'Cooking', topic: 'Do you have a favorite chef or cooking show?', used: false },
  { interest: 'Cooking', topic: 'What\'s the most unusual ingredient you\'ve cooked with?', used: false },
  { interest: 'Cooking', topic: 'Do you grow any of your own herbs or vegetables?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite kitchen gadget?', used: false },
  { interest: 'Cooking', topic: 'Have you ever cooked a meal for a large group?', used: false },
  { interest: 'Cooking', topic: 'What\'s your opinion on meal prep?', used: false },
  { interest: 'Cooking', topic: 'Do you have a favorite cookbook?', used: false },
  { interest: 'Cooking', topic: 'What\'s the best meal you\'ve ever had at a restaurant?', used: false },
  { interest: 'Cooking', topic: 'Have you ever tried molecular gastronomy?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite spice or seasoning?', used: false },
  { interest: 'Cooking', topic: 'Do you have any dietary restrictions or preferences?', used: false },
  { interest: 'Cooking', topic: 'What\'s your opinion on fusion cuisine?', used: false },
  { interest: 'Cooking', topic: 'Have you ever foraged for ingredients?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite type of cheese?', used: false },
  { interest: 'Cooking', topic: 'Do you have a signature dish?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite cooking method (grilling, roasting, etc.)?', used: false },
  { interest: 'Cooking', topic: 'Have you ever made your own bread from scratch?', used: false },
  { interest: 'Cooking', topic: 'What\'s your favorite food-related memory?', used: false },

  // Sports (25 topics)
  { interest: 'Sports', topic: 'What\'s your favorite sport to watch or play?', used: false },
  { interest: 'Sports', topic: 'Do you have a favorite athlete? Who and why?', used: false },
  { interest: 'Sports', topic: 'What\'s the most exciting sporting event you\'ve attended?', used: false },
  { interest: 'Sports', topic: 'Do you think esports should be considered real sports?', used: false },
  { interest: 'Sports', topic: 'What\'s your opinion on performance-enhancing drugs in sports?', used: false },
  { interest: 'Sports', topic: 'Have you ever participated in a marathon or similar event?', used: false },
  { interest: 'Sports', topic: 'What\'s your favorite Olympic sport?', used: false },
  { interest: 'Sports', topic: 'Do you have a favorite sports team? Why do you support them?', used: false },
  { interest: 'Sports', topic: 'What\'s the most unusual sport you\'ve ever heard of or tried?', used: false },
  { interest: 'Sports', topic: 'Do you think professional athletes are overpaid?', used: false },
  { interest: 'Sports', topic: 'What\'s your opinion on sports betting?', used: false },
  { interest: 'Sports', topic: 'Have you ever met a professional athlete?', used: false },
  { interest: 'Sports', topic: 'What\'s your favorite sports movie?', used: false },
  { interest: 'Sports', topic: 'Do you follow any extreme sports?', used: false },
  { interest: 'Sports', topic: 'What\'s your opinion on the use of technology in sports officiating?', used: false },
  { interest: 'Sports', topic: 'Have you ever been part of a sports team?', used: false },
  { interest: 'Sports', topic: 'What\'s your favorite sports-related memory?', used: false },
  { interest: 'Sports', topic: 'Do you think certain sports should be added to or removed from the Olympics?', used: false },
  { interest: 'Sports', topic: 'What\'s your opinion on the pay gap in men\'s and women\'s sports?', used: false },
  { interest: 'Sports', topic: 'Have you ever tried a water sport?', used: false },
  { interest: 'Sports', topic: 'What\'s your favorite winter sport?', used: false },
  { interest: 'Sports', topic: 'Do you have a favorite sports commentator or analyst?', used: false },
  { interest: 'Sports', topic: 'What\'s your opinion on sports superstitions?', used: false },
  { interest: 'Sports', topic: 'Have you ever attended a sports fantasy camp?', used: false },
  { interest: 'Sports', topic: 'What\'s the most impressive sports feat you\'ve witnessed?', used: false },

  // Travel (25 topics)
  { interest: 'Travel', topic: 'What\'s your dream travel destination?', used: false },
  { interest: 'Travel', topic: 'Do you prefer beach vacations or city trips?', used: false },
  { interest: 'Travel', topic: 'What\'s the most memorable place you\'ve ever visited?', used: false },
  { interest: 'Travel', topic: 'Do you enjoy solo travel or traveling with others?', used: false },
  { interest: 'Travel', topic: 'What\'s your opinion on eco-tourism?', used: false },
  { interest: 'Travel', topic: 'Have you ever been on a road trip? Where did you go?', used: false },
  { interest: 'Travel', topic: 'What\'s your favorite mode of transportation when traveling?', used: false },
  { interest: 'Travel', topic: 'Do you have any travel hacks or tips?', used: false },
  { interest: 'Travel', topic: 'What\'s the most unusual place you\'ve ever stayed?', used: false },
  { interest: 'Travel', topic: 'Do you collect souvenirs when you travel?', used: false },
  { interest: 'Travel', topic: 'What\'s your opinion on all-inclusive resorts?', used: false },
  { interest: 'Travel', topic: 'Have you ever experienced culture shock while traveling?', used: false },
  { interest: 'Travel', topic: 'What\'s your favorite travel app?', used: false },
  { interest: 'Travel', topic: 'Do you prefer to plan your trips in detail or go with the flow?', used: false },
  { interest: 'Travel', topic: 'What\'s the most adventurous thing you\'ve done while traveling?', used: false },
  { interest: 'Travel', topic: 'Have you ever volunteered abroad?', used: false },
  { interest: 'Travel', topic: 'What\'s your favorite cuisine you\'ve tried while traveling?', used: false },
  { interest: 'Travel', topic: 'Do you think travel is important for personal growth?', used: false },
  { interest: 'Travel', topic: 'What\'s your opinion on sustainable travel?', used: false },
  { interest: 'Travel', topic: 'Have you ever learned a new language for a trip?', used: false },
  { interest: 'Travel', topic: 'What\'s your favorite travel memory?', used: false },
  { interest: 'Travel', topic: 'Do you prefer to travel domestically or internationally?', used: false },
  { interest: 'Travel', topic: 'What\'s the most beautiful natural wonder you\'ve seen?', used: false },
  { interest: 'Travel', topic: 'Have you ever been on a cruise?', used: false },
  { interest: 'Travel', topic: 'What\'s your opinion on travel influencers?', used: false },

  // Art (25 topics)
  { interest: 'Art', topic: 'What\'s your favorite art style or movement?', used: false },
  { interest: 'Art', topic: 'Do you have a favorite artist? Who and why?', used: false },
  { interest: 'Art', topic: 'What\'s your opinion on modern art?', used: false },
  { interest: 'Art', topic: 'Have you ever created art yourself? What medium?', used: false },
  { interest: 'Art', topic: 'What\'s the most impressive art exhibition you\'ve attended?', used: false },
  { interest: 'Art', topic: 'Do you think art should be political?', used: false },
  { interest: 'Art', topic: 'What\'s your favorite type of visual art (painting, sculpture, etc.)?', used: false },
  { interest: 'Art', topic: 'Have you ever bought an original piece of art?', used: false },
  { interest: 'Art', topic: 'What\'s your opinion on street art and graffiti?', used: false },
  { interest: 'Art', topic: 'Do you think AI-generated art is real art?', used: false },
  { interest: 'Art', topic: 'What\'s your favorite art museum?', used: false },
  { interest: 'Art', topic: 'Have you ever taken an art class?', used: false },
  { interest: 'Art', topic: 'What\'s your opinion on the value of some artworks?', used: false },
  { interest: 'Art', topic: 'Do you have a favorite art period in history?', used: false },
  { interest: 'Art', topic: 'What\'s the role of art in society, in your opinion?', used: false },
  { interest: 'Art', topic: 'Have you ever been to an art auction?', used: false },
  { interest: 'Art', topic: 'What\'s your favorite color palette in art?', used: false },
  { interest: 'Art', topic: 'Do you think everyone can be an artist?', used: false },
  { interest: 'Art', topic: 'What\'s your opinion on digital art?', used: false },
  { interest: 'Art', topic: 'Have you ever been inspired by a piece of art?', used: false },
  { interest: 'Art', topic: 'What\'s your favorite public art installation?', used: false },
  { interest: 'Art', topic: 'Do you think art education is important in schools?', used: false },
  { interest: 'Art', topic: 'What\'s your opinion on art restoration?', used: false },
  { interest: 'Art', topic: 'Have you ever participated in an art workshop?', used: false },
  { interest: 'Art', topic: 'What\'s the most unusual art piece you\'ve ever seen?', used: false },

  // Books (25 topics)
  { interest: 'Books', topic: 'What\'s your favorite book of all time?', used: false },
  { interest: 'Books', topic: 'Do you prefer physical books, e-books, or audiobooks?', used: false },
  { interest: 'Books', topic: 'Who\'s your favorite author and why?', used: false },
  { interest: 'Books', topic: 'What genre do you enjoy reading the most?', used: false },
  { interest: 'Books', topic: 'Have you ever been part of a book club?', used: false },
  { interest: 'Books', topic: 'What\'s the last book that made you cry or laugh out loud?', used: false },
  { interest: 'Books', topic: 'Do you think classic literature is still relevant today?', used: false },
  { interest: 'Books', topic: 'What\'s your opinion on film adaptations of books?', used: false },
  { interest: 'Books', topic: 'Have you ever met an author at a book signing?', used: false },
  { interest: 'Books', topic: 'What\'s your favorite bookstore?', used: false },
  { interest: 'Books', topic: 'Do you have a favorite literary character?', used: false },
  { interest: 'Books', topic: 'What book has had the biggest impact on your life?', used: false },
  { interest: 'Books', topic: 'Do you enjoy re-reading books?', used: false },
  { interest: 'Books', topic: 'What\'s your opinion on self-help books?', used: false },
  { interest: 'Books', topic: 'Have you ever tried writing a book yourself?', used: false },
  { interest: 'Books', topic: 'What\'s your favorite book-to-movie adaptation?', used: false },
  { interest: 'Books', topic: 'Do you think print books will eventually become obsolete?', used: false },
  { interest: 'Books', topic: 'What\'s your opinion on banned books?', used: false },
  { interest: 'Books', topic: 'Have you ever read a book in a language other than your native tongue?', used: false },
  { interest: 'Books', topic: 'What\'s your favorite opening line from a book?', used: false },
  { interest: 'Books', topic: 'Do you have a favorite literary quote?', used: false },
  { interest: 'Books', topic: 'What\'s your opinion on fan fiction?', used: false },
  { interest: 'Books', topic: 'Have you ever attended a literary festival?', used: false },
  { interest: 'Books', topic: 'What\'s the most challenging book you\'ve ever read?', used: false },
  { interest: 'Books', topic: 'Do you think reading fiction can increase empathy?', used: false },

  // Movies (25 topics)
  { interest: 'Movies', topic: 'What\'s your all-time favorite movie?', used: false },
  { interest: 'Movies', topic: 'Do you prefer watching movies at home or in the theater?', used: false },
  { interest: 'Movies', topic: 'Who\'s your favorite director and why?', used: false },
  { interest: 'Movies', topic: 'What genre of movies do you enjoy the most?', used: false },
  { interest: 'Movies', topic: 'Have you ever been an extra in a movie?', used: false },
  { interest: 'Movies', topic: 'What\'s the last movie that made you cry or laugh uncontrollably?', used: false },
  { interest: 'Movies', topic: 'Do you think movies should always have a message or can they just be entertainment?', used: false },
  { interest: 'Movies', topic: 'What\'s your opinion on remakes and reboots?', used: false },
  { interest: 'Movies', topic: 'Have you ever met a famous actor or actress?', used: false },
  { interest: 'Movies', topic: 'What\'s your favorite movie soundtrack?', used: false },
  { interest: 'Movies', topic: 'Do you have a favorite movie character?', used: false },
  { interest: 'Movies', topic: 'What movie has had the biggest impact on your life?', used: false },
  { interest: 'Movies', topic: 'Do you enjoy watching foreign films?', used: false },
  { interest: 'Movies', topic: 'What\'s your opinion on the current state of the film industry?', used: false },
  { interest: 'Movies', topic: 'Have you ever walked out of a movie theater?', used: false },
  { interest: 'Movies', topic: 'What\'s your favorite movie quote?', used: false },
  { interest: 'Movies', topic: 'Do you think streaming services are good or bad for cinema?', used: false },
  { interest: 'Movies', topic: 'What\'s your opinion on product placement in movies?', used: false },
  { interest: 'Movies', topic: 'Have you ever been to a film festival?', used: false },
  { interest: 'Movies', topic: 'What\'s the most visually stunning movie you\'ve seen?', used: false },
  { interest: 'Movies', topic: 'Do you stay for post-credit scenes?', used: false },
  { interest: 'Movies', topic: 'What\'s your opinion on method acting?', used: false },
  { interest: 'Movies', topic: 'Have you ever done a movie marathon?', used: false },
  { interest: 'Movies', topic: 'What\'s the most quotable movie in your opinion?', used: false },
  { interest: 'Movies', topic: 'Do you think movies can change society?', used: false },

  // Games (25 topics)
  { interest: 'Games', topic: 'What\'s your favorite video game of all time?', used: false },
  { interest: 'Games', topic: 'Do you prefer console gaming, PC gaming, or mobile gaming?', used: false },
  { interest: 'Games', topic: 'What\'s your favorite game genre?', used: false },
  { interest: 'Games', topic: 'Have you ever been to a gaming convention?', used: false },
  { interest: 'Games', topic: 'What\'s your opinion on microtransactions in games?', used: false },
  { interest: 'Games', topic: 'Do you enjoy multiplayer or single-player games more?', used: false },
  { interest: 'Games', topic: 'What\'s the most challenging game you\'ve ever played?', used: false },
  { interest: 'Games', topic: 'Have you ever speedrun a game?', used: false },
  { interest: 'Games', topic: 'What\'s your favorite game soundtrack?', used: false },
  { interest: 'Games', topic: 'Do you think video games can be educational?', used: false },
  { interest: 'Games', topic: 'What\'s your opinion on game streaming platforms like Twitch?', used: false },
  { interest: 'Games', topic: 'Have you ever rage-quit a game?', used: false },
  { interest: 'Games', topic: 'What\'s your favorite game character?', used: false },
  { interest: 'Games', topic: 'Do you enjoy watching esports?', used: false },
  { interest: 'Games', topic: 'What\'s your opinion on virtual reality gaming?', used: false },
  { interest: 'Games', topic: 'Have you ever modded a game?', used: false },
  { interest: 'Games', topic: 'What\'s the longest gaming session you\'ve ever had?', used: false },
  { interest: 'Games', topic: 'Do you think games should have more diverse representation?', used: false },
  { interest: 'Games', topic: 'What\'s your favorite indie game?', used: false },
  { interest: 'Games', topic: 'Have you ever participated in a game jam?', used: false },
  { interest: 'Games', topic: 'What\'s your opinion on game remasters and remakes?', used: false },
  { interest: 'Games', topic: 'Do you enjoy narrative-driven games or gameplay-focused games more?', used: false },
  { interest: 'Games', topic: 'What\'s the most emotional moment you\'ve experienced in a game?', used: false },
  { interest: 'Games', topic: 'Have you ever cosplayed as a game character?', used: false },
  { interest: 'Games', topic: 'What do you think is the future of gaming?', used: false },
  // ... (continue with 25 topics for each of the remaining interests: Animals, Cooking, Sports, Travel, Art, Books, Movies, Games)
];